---
title: "ass3"
output: html_document
date: "2023-04-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(
  tidyverse,
  brms,
  cmdstanr,
  patchwork
)
source("SimpleBayes_f.R")
source("WeightedBayes_f.R")
```


```{r}
# setting up experimental loop - simple bayes
ntrials <- 100
bias <- 0.5
rating <- c(1,2,3,4,5,6,7,8)
diff <- c(-3, -2, 0, 2, 3)
# saving info
Source1 <- array(NA, ntrials)
Source2 <- array(NA, ntrials)
diff_t <- array(NA, ntrials)
feedback <- array(NA, ntrials)
choice1 <- array(NA, ntrials)
choice2 <- array(NA, ntrials)
temp_c <- array(NA, ntrials)
for (i in 1:ntrials){
  # create random first choice
  choice1[i] <- sample(rating, 1, replace=TRUE)
  # make it on 0-1 space 
  Source1[i] <- choice1[i]/9
  # create feedback information, i.e., group rating
  feedback[i] <- 0
  while (feedback[i] < 1 | feedback[i] > 8){ # while group rating out of scope
    # sample a difference from choice1
    diff_t[i] <- sample(diff, 1, replace=TRUE)
    
    # make the other choice / group rating
    feedback[i] <- choice1[i] + diff_t[i]
    }
  
  # get group rating to 0-1 space
  Source2[i] <- feedback[i]/9
  # get the second choice 
  temp_c[i] <- SimpleBayes_f(bias, Source1[i], Source2[i])
  # fixing the thing with the out of bounds choices
  choice2[i] <- ifelse(round(temp_c[i]*9,0) < 1, 1, 
                     ifelse(round(temp_c[i]*9,0) > 8, 8, 
                            round(temp_c[i]*9,0)))
}
s_df <- tibble(trial = seq(ntrials), bias, choice1, choice2, Source1, Source2, 
               feedback, diff_t, temp_c)
```


```{r}
# setup for weighted bayes
ntrials <- 100
bias <- 0
w1 <- 0.2
w2 <- 0.8
rating <- c(1,2,3,4,5,6,7,8)
diff <- c(-3, -2, 0, 2, 3)
# saving info
Source1 <- array(NA, ntrials)
Source2 <- array(NA, ntrials)
diff_t <- array(NA, ntrials)
feedback <- array(NA, ntrials)
choice1 <- array(NA, ntrials)
choice2 <- array(NA, ntrials)
temp_c <- array(NA, ntrials)
for (i in 1:ntrials){
  # make first choice
  choice1[i] <- sample(rating, 1, replace=TRUE)
  # make it 0-1 scale
  Source1[i] <- choice1[i]/9
  
  # generate other choice
  feedback[i] <- 0
  while (feedback[i] < 1 | feedback[i] > 8){
    diff_t[i] <- sample(diff, 1, replace=TRUE)
    
    feedback[i] <- choice1[i] + diff_t[i]
    }
 
  # scale it
  Source2[i] <- feedback[i]/9
  
  # choice 2
  temp_c[i] <- WeightedBayes_f(bias, Source1[i], Source2[i], w1, w2)
  
  # make sure it's inside bounds 
  choice2[i] <- ifelse(round(temp_c[i]*9,0) < 1, 1, 
                     ifelse(round(temp_c[i]*9,0) > 8, 8, 
                            round(temp_c[i]*9,0)))
}
w_df <- tibble(trial = seq(ntrials), bias, w1, w2, choice1, choice2, Source1, Source2, 
               feedback, diff_t, temp_c)
```

```{r}
# prepare data for stan - simple bayes
data_simpleBayes <- list(
  N = nrow(s_df),
  choice = s_df$choice2, # the outcome of combining choice1 and group rating
  Source1 = s_df$Source1, # own rating on 0-1 space
  Source2 = s_df$Source2 # group raing on 0-1 space
)
# feed R the stan model
file <- file.path("simplebayes.stan")
mod_simpleBayes <- cmdstan_model(file, cpp_options = list(stan_threads = TRUE),
                     stanc_options = list("O1"))
samples_simple <- mod_simpleBayes$sample(
  data = data_simpleBayes,
  #fixed_param = TRUE,
  seed = 123,
  chains = 2,
  parallel_chains = 2,
  threads_per_chain = 2,
  iter_warmup = 1500,
  iter_sampling = 3000,
  refresh = 500
)
# basic evaluation
samples_simple$cmdstan_diagnose()
```

```{r}
# diagnostics
samples_simple$summary()
samples_simple$loo()
draws_df <- as_draws_df(samples_simple$draws())
ggplot(draws_df, aes(.iteration, bias, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
ggplot(draws_df) +
  geom_density(aes(bias), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(bias_prior), alpha = 0.6, fill = "pink") +
  geom_vline(xintercept = s_df$bias[1]) +
  theme_bw()
ggplot(draws_df) +
  geom_density(aes(sd), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(sd_prior), alpha = 0.6, fill = "pink") +
  geom_vline(xintercept = s_df$bias[1]) +
  theme_bw()
```
```{r}
# prepare data for stan - weighted bayes
data_weightedBayes <- list(
  N = nrow(w_df),
  choice = w_df$choice2, # the outcome of combining choice1 and group rating
  Source1 = w_df$Source1, # own rating on 0-1 space
  Source2 = w_df$Source2 # group raing on 0-1 space
)
# feed R the stan model
file <- file.path("weighted_bayes.stan")
mod_weightedBayes <- cmdstan_model(file, cpp_options = list(stan_threads = TRUE),
                     stanc_options = list("O1"))
samples_weight <- mod_weightedBayes$sample(
  data = data_weightedBayes,
  #fixed_param = TRUE,
  seed = 123,
  chains = 2,
  parallel_chains = 2,
  threads_per_chain = 2,
  iter_warmup = 1500,
  iter_sampling = 3000,
  refresh = 500
)
# basic evaluation
samples_weight$cmdstan_diagnose()
```
```{r}
# diagnostics
samples_weight$summary()
samples_weight$loo()
draws_df <- as_draws_df(samples_weight$draws())
ggplot(draws_df, aes(.iteration, bias, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
ggplot(draws_df) +
  geom_density(aes(bias), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(bias_prior), alpha = 0.6, fill = "pink") +
  geom_vline(xintercept = w_df$bias[1]) +
  theme_bw()
ggplot(draws_df) +
  geom_density(aes(w1), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(w1_prior), alpha = 0.6, fill = "pink") +
  geom_vline(xintercept = w_df$w1[1]) +
  theme_bw()
ggplot(draws_df) +
  geom_density(aes(w2), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(w2_prior), alpha = 0.6, fill = "pink") +
  geom_vline(xintercept = w_df$w2[1]) +
  theme_bw()
```


```{r}
# loading empirical data
data_path <- "Data/cogsci_clean.csv"
df_cs <- read_csv(data_path)
```

```{r}
# fitting simple bayes to empirical data 
for (i in seq(6)){
  df_temp <- df_cs %>% 
    filter(ID == i, GroupRating != 0) %>% 
    mutate(Source1 = FirstRating/9,
           Source2 = GroupRating/9)
  
  data_list <- list(
    N = nrow(df_temp),
    choice = df_temp$SecondRating, # outcome of combining both information sources
    Source1 = df_temp$Source1,
    Source2 = df_temp$Source2
  )
  file <- file.path("simplebayes.stan")
  mod_weightedBayes <- cmdstan_model(file, cpp_options = list(stan_threads = TRUE),
                                     stanc_options = list("O1"))
  
  samples <- mod_weightedBayes$sample(
    data = data_list,
    #fixed_param = TRUE,
    seed = 123,
    chains = 2,
    parallel_chains = 2,
    threads_per_chain = 2,
    iter_warmup = 1500,
    iter_sampling = 3000,
    refresh = 500
  )
  
  temp <- as_draws_df(samples$draws())
  temp <- temp %>% 
    mutate(ID = i)
  
  if (exists("draws_df_emp")) { draws_df_emp <- rbind(draws_df_emp, temp)} 
  else{draws_df_emp <- temp} 
}
```

```{r}
# diagnostics
ggplot(draws_df_emp, aes(.iteration, bias, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
ggplot(draws_df_emp, aes(.iteration, sd, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
draws_df_emp %>% 
  ggplot() +
    geom_density(aes(bias), alpha = 0.6, fill = "lightblue")+
    geom_density(aes(bias_prior), alpha = 0.6, fill = "pink")+
    facet_wrap(~ID)+
    theme_bw()
draws_df_emp %>% 
  ggplot() +
    geom_density(aes(sd), alpha = 0.6, fill = "lightblue")+
    geom_density(aes(sd_prior), alpha = 0.6, fill = "pink")+
    facet_wrap(~ID)+
    theme_bw()
```

```{r}
# fitting weighted bayes to empirical data 
for (i in seq(6)){
  df_temp <- df_cs %>% 
    filter(ID == i, GroupRating != 0) %>% 
    mutate(Source1 = FirstRating/9,
           Source2 = GroupRating/9)
  
  data_list <- list(
    N = nrow(df_temp),
    choice = df_temp$SecondRating, # outcome of combining both information sources
    Source1 = df_temp$Source1,
    Source2 = df_temp$Source2
  )
  file <- file.path("weighted_bayes.stan")
  mod_weightedBayes <- cmdstan_model(file, cpp_options = list(stan_threads = TRUE),
                                     stanc_options = list("O1"))
  
  samples <- mod_weightedBayes$sample(
    data = data_list,
    #fixed_param = TRUE,
    seed = 123,
    chains = 2,
    parallel_chains = 2,
    threads_per_chain = 2,
    iter_warmup = 1500,
    iter_sampling = 3000,
    refresh = 500
  )
  
  temp <- as_draws_df(samples$draws())
  temp <- temp %>% 
    mutate(ID = i)
  
  if (exists("draws_df_emp2")) { draws_df_emp2 <- rbind(draws_df_emp2, temp)} 
  else{draws_df_emp2 <- temp} 
}
```

```{r}
# diagnostics
ggplot(draws_df_emp2, aes(.iteration, bias, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
ggplot(draws_df_emp2, aes(.iteration, sd, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
draws_df_emp2 %>% 
  ggplot() +
    geom_density(aes(bias), alpha = 0.6, fill = "lightblue")+
    geom_density(aes(bias_prior), alpha = 0.6, fill = "pink")+
    facet_wrap(~ID)+
    theme_bw()
draws_df_emp2 %>% 
  ggplot() +
    geom_density(aes(sd), alpha = 0.6, fill = "lightblue")+
    geom_density(aes(sd_prior), alpha = 0.6, fill = "pink")+
    facet_wrap(~ID)+
    theme_bw()
draws_df_emp2 %>% 
  ggplot() +
    geom_density(aes(w1), alpha = 0.6, fill = "lightblue")+
    geom_density(aes(w1_prior), alpha = 0.6, fill = "pink")+
    facet_wrap(~ID)+
    theme_bw()
draws_df_emp2 %>% 
  ggplot() +
    geom_density(aes(w2), alpha = 0.6, fill = "lightblue")+
    geom_density(aes(w2_prior), alpha = 0.6, fill = "pink")+
    facet_wrap(~ID)+
    theme_bw()
```